excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://rsslrt.github.io
title: La SiliconValley de Nojaltri
tagline: L'Information Technology, ciapà a scarpade.
description: 'Na onta (e 'na ponta) de veneto so un mondo fin massa anglocentrico.
paginate: 5